Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/10/2024
Var
// Seção de Declarações das variáveis 
ata= caractere
num= inteiro


Inicio
escreval("escreva o seu nome")
leia(ata)
escreval("idade")
leia(num)

Fimalgoritmo